### PR TITLE
Code adapted from https://github.com/EagleoutIce/SlideTemplate/pull/7

### LINKED ISSUE #26: Make Content Layouts Verbatim-Safe
Currently verbatim environments like `lstlisting` do not work inside content layouts like `\leftandright`.

### LINKED ISSUE #34: Empty titles in colored boxes waste space and look weird
grafik

On the left is the current rendering, whereas the rendering of my old template is shown on the right.

### PR DESCRIPTION
**Pull request by EagleoutIce**
This closes #26 (and closes #34) and adds several features while staying completely backwards compatible (except for special tex-hacky cases because we rely on different internal definitions):

* For the old macros `\mydefinition`, `\mydefinitiontight` etc. there are now environments
  `definition` and `definitiontight` which are verbatim-safe (i added an example to the demo-slides).
* All splits (e.g.,  `leftmiddleandright`) can be used either as macro (just like before) or as
  a verbatim-safe variant.
  
  The mechanism used to check this is not completely safe, but the technique is widespread
  and e.g. used by beamer itself and several other packages. Some tex-hackery is
  needed to break it.

Furthermore, I have documented the procedure.

### CODE REVIEW

**Comment by EagleoutIce** [comment]
Closes #34 too.

**Comment by Benno2000** [comment]
Your solution seems to work, however, i don't really like the idea of having both options in the final template. I also think the way it was done before it was more understandable for a non-expert user. Is this the only way to make colorboxes verbatim-safe?

**Comment by EagleoutIce** [comment]
Yes, the solution does work ^^. 
The reason for retaining the old option with `\mydefinition` is due to a wish of @tthuem.
Nevertheless, using macros for verbatim content is always a problem as their arguments are consumed by tex, requiring catcode-magic in order for special characters, whitespaces etc. to survive. 
The easiest solution would be to remove the old mechanism in favor of an environment-based approach (non-collecting environments are ""verbatim-safe"" simply because they do not trigger tex to consume their content with the initial `\begin`). 

The PR introduces one "complex" fragment (which is a standard procedure in order to achieve the effect) to determine if the user wants `\begin{box} ... ` or `\box{...}`. This can be easily removed when either the environment or the macro-approach is removed. However, using the original macro-approach for the boxes would require catcode-magic in our code to make them verbatim safe.

**Comment by Benno2000** [comment]
- Regarding backwards-compatibility: If it is definitely not possible to use the macros with verbatim content, I would rather remove those from the template and replace them with an environment-based approach. To keep the old slides (that use the macros) working, I believe we could just put their definition into the lecture-specific `lecture.tex`-file.

- Regarding the environments: If an environment-based solution should work, why doesn't the following simple approach work with verbatim content?
```
\newenvironment{mydefinition}[1][]{
    \begin{tcolorbox}[title={\setlength{\parskip}{0ex}\vphantom{/}#1},colback=orange!10,colframe=orange!30,coltitle=black,fonttitle=\bfseries,left=1mm,right=1mm,top=1mm,bottom=1mm]
}{
    \end{tcolorbox}
}
```

**Comment by EagleoutIce** [comment]
Your definition does work:

Screenshot_20220829_125940

But:
1. You must mark the frame as fragile (there is no changing that, you could however mark all frames as fragile)
2. You can't use the environment within the argument of another macro - tex's way of consuming macros is the whole problem :D

Screenshot_20220829_125953

That is why i updated the splitter environments as well:

```latex
\begin{leftmiddleandright}
	\begin{definition}{A Definition}
		This is a definition.
\begin{minted}{java}
System.out.println("foo");
\end{minted}
	\end{definition}
\second
	\myexample{An Example}{This is an example.}
\third
	\begin{note}{A Note}
		This is a note.
	\end{note}
\end{leftmiddleandright}
```


As stated before, we 'could' make specific macros safe to be used with verbatim content, but this would a) require *a lot* of hackery that is far more complex than what this PR offers and b) be prone to a lot of errors.

**Comment by EagleoutIce** [comment]
I will update this due to https://github.com/SoftVarE-Group/SlideTemplate/issues/26#issuecomment-1237695164 and open a new PR.

**Pull request closed without merging**
