### PR TITLE
customizable colored boxes

### PR DESCRIPTION
**Pull request by EagleoutIce**
t

### CODE REVIEW

**Comment by tthuem** [comment]
@Benno2000 What is the plan for this PR?

**Comment by Benno2000** [comment]
Overall, I like the way to define custom boxes and also use counters. But currently it is not possible for me to define boxes before `\begin{document}`, which would be helpful to define custom boxes e.g. in the lecture.tex file that is included before `\begin{document}`.

**Comment by EagleoutIce** [comment]
What kind of error do you get? there should be no problem writing something like
`\MakeNewBox{hello}{green}` into the preamble.
Just make sure it happens after the uulm beamer theme is loaded.

**Comment by EagleoutIce** [comment]
You are correct, i missed this (although this would not have posed any problems it certainly is irritating!)

I have added the missing closing brace.

**Comment by Benno2000** [comment]
Perfect, thanks! 
So we can merge this PR now? (What do you think @tthuem?)

**Review by Benno2000 — APPROVED** [review]

**Pull request merged**
