### PR TITLE
custom logos

### PR DESCRIPTION
**Pull request by EagleoutIce**
Two new commands to set the logo[^1]:

```latex
\institutelogo[<includegraphics>]{<filename>}
\universitylogo[<includegraphics>]{<filename>}
```

Furthermore, two additional commands to remove the logo:

```latex
\clearinstitutelogo
\clearuniversitylogo
```

The default is:

```latex
\universitylogo{uulm}
\clearinstitutelogo
```

Including the sp-logo is easy with just: `\institutelogo{sp}` (i added lines to the demoSlides which are commented-out).

If someone adds a custom image it will be scaled to the same height. It is up to the user to ensure, that the scaled image remains readable and of a reasonable width (we could constraint that, or add some clippings, but at least in my opinion, that would only unnecessary complicate the code). 

[^1]: With `<includegraphics>`, I refer to additional options accepted by the `\includegraphics`-command (e.g. `width=.5\linewidth, keepaspectratio`).

### CODE REVIEW

**Review by tthuem — APPROVED** [review]
Looks great!

**Comment by Benno2000** [comment]
Looks good to me! However I am not sure if we even need the commands to clear the logo when we for example can just use `\institutelogo{}`.

**Comment by EagleoutIce** [comment]
`\uulmlogos{sp,sp,uulm}` - mehrere Logos (gehen beliebig viele, ich prüfe aber nicht, ob deren horizontaler Platz passt, das muss man dann selbst entscheiden
`\uulmlogos{sp}` - nur SP, wie `\institutelogo{sp}\clearuniversitylogo`
`\uulmlogos{,uulm}` - nur Uni Ulm Logo, rechts, wie `\universitylogo{uulm}\clearuniversitylogo`
`\uulmlogos{sp,uulm}` - der "bisherige" Stand
`\uulmlogos{,sp,}` - ein zentriertes Logo

Problem: wenn die Logos unterschiedlich hoch sein sollen, setzt `\uulmlogos[<opts>]{...}`bisher die defaults für Alle.

Vorherige Anweisungen mit `\institutelogo` usw werden überschrieben.

**Comment by tthuem** [comment]
@Benno2000 Please go ahead an merge this.

**Pull request merged**
